#!/bin/sh
#
#  Launch the application.
#
#  1.  If we're launched by a username of the form /^s-dns/ then
#     we bind to the port of the user-id.
#
#  2.  We log to logs/$(date).log
#
#


# Default port
port=5001

# Launch
echo "Launching on Port $port"
exec plackup -s Twiggy --workers=4 -p $port -a ./bin/dns-api -E production
